# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
