# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_auto_20170319_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
